version: "3"

name: "all_task"

services:
    pickle_rce:
        container_name: pickle-rce
        build:
            context: ./pickle-rce/task
        ports:
            -  "31337:8888"
    # off_by_slash:
    app:
        container_name: off-by-slash
        build:
            context: ./Off-By-Slash/task
        ports:
            -  "31338:80"
    xxe:
        container_name: xxe
        build:
            context: ./xxe/task
        ports:
            -  "31339:8888"