version: "3"

name: "task_race_cond"

services:
    app:
       build:
           context: .
       ports:
           -  "1337:8000"
    # nginx: 
    #     image: nginx:latest
    #     volumes:
    #     - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    #     - ./app/static/:/app/static/:ro
    #     depends_on:
    #     - app
    #     ports:
    #     - "80:80"
