version: "3"

name: "task1"

services:
    app:
       build:
           context: .
       ports:
           -  "8888"
    nginx: 
        image: nginx:latest
        volumes:
        - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
        - ./app/static/:/app/static/:ro
        depends_on:
        - app
        ports:
        - "80:80"
