version: "3"

name: "task_safe_eval_weak"

services:
    app:
        container_name: "task_safe_eval_weak"
        restart: unless-stopped
        build:
            context: .
        ports:
            -  "24244:8888"
    # nginx: 
    #     image: nginx:latest
    #     volumes:
    #     - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    #     - ./app/static/:/app/static/:ro
    #     depends_on:
    #     - app
    #     ports:
    #     - "80:80"
