version: "3"

name: "proxy"

services:
    app:
        container_name: "proxy-app"
        restart: unless-stopped
        build:
            context: .
        ports:
            -  "31332:8888"
    intranet:
        container_name: "proxy-intranet"
        restart: unless-stopped
        build:
            context: ./app-localhost
    google.com:
        container_name: "proxy-internet"
        build:
            context: ./app-internet
#    nginx:
#        image: nginx:latest
#        volumes:
#        - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
#        - ./app/static/:/app/static/:ro
#        depends_on:
#        - app
#        ports:
#        - "31332:80"
