version: "3"

name: "proxy"

services:
    app:
       build:
           context: .
       ports:
           -  "31332:8888"
    intranet:
       build:
           context: ./app-localhost
    google.com:
       build:
           context: ./app-internet
#    nginx:
#        image: nginx:latest
#        volumes:
#        - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
#        - ./app/static/:/app/static/:ro
#        depends_on:
#        - app
#        ports:
#        - "31332:80"
