version:                "3.8"
services:
    goldinospizza:
        container_name: goldinospizza
        hostname:       goldinospizza
        image:          goldinospizza
        build:          .
        ports:
            - 4242:8000
        restart:        unless-stopped
        environment:
            - FLAG=ptm{flag}
        # secrets:
        #    - key
        #    - cert

# secrets:
#    key:
#        file:            ./flask/key.pem
#    cert:
#        file:            ./flask/cert.pem
