version: "3"

name: "task_ssti"

services:
    app:
        container_name: "task_ssti"
        restart: unless-stopped
        build:
            context: .
        ports:
            -  "31331:8888"
#    nginx:
#        image: nginx:latest
#        volumes:
#        - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
#        - ./app/static/:/app/static/:ro
#        depends_on:
#        - app
#        ports:
#        - "31331:80"
